config/config.json, config/endPoint.json
=> add config and end point

.gitignore, endpoints/appearanceEndPoint.json, lib/appearanceLib.js, requestJSONs/appearanceRequest.json, test/smoke/appearanceST.js
Added 2 smoke tests for tablet appearance.
Added appearanceLib
Added the request and endpoint files for appearance.
P.S.: I'm uploading this so that at the end of the day it wouldn't be hard to review all the code.
=> Appearance feature files

lib/conferenceRoomsLib.js, test/crud/conferenceRoomsCT.js, test/smoke/conferenceRoomsST.js
=> Corrected refactor and title

lib/resourcesLib.js, requestJSONs/resourcesRequests.json, test/crud/resourcesCT.js, test/smoke/resourcesST.js
CRUD test case to verify the creation of a resource
=> CRUD test case

package.json, requestJSONs/resourcesRequests.json, test/crud/resourcesCT.js
The connection to the database is working, this is the GET resource api test case using the DB.
The package json was also modified, and there are other small changes in the comments and configuration files.
=> crud test case get resource

endpoints/locationsEndPoint.json, lib/locationsLib.js, test/crud/locationsCT.js, test/smoke/locationsST.js
Last crud test for GET method to obtain all exiting locations implemented, and suggested corrections done
=> Crud tests finished

config/endPoint.json
I changed the angle brackets for square brackets, that might be the problem that were crashing the app.
=> Fixing the config/endPoint file

requestJSONs/resourcesRequests.json
A change in one of the fields of resourceRequest.json
=> changes in resourceRequest.json

test/smoke/impersonationST.js
Done problem on impersonationST.js fixed
=> impersonationST.js Fixed

lib/tokenLib.js
I added the option to set between local and domain account.
=> Added a change to tokenLib

test/crud/resourcesCT.js
All the crud test cases are now implemented
-create a resource
-get a resource
-get all resources
-update a resource
-delete a resource
=> crud test cases

.gitignore, settings.json, test/crud/servicesCT.js, test/smoke/servicesSt.js
all Smoke tests are running fine
=> I tested all Smokes

settings.json, test/smoke/locationsST.js
setting timeout on locationsST
=> Correcting timeout on Paola's Smoke tests

lib/mongoConnection.js, test/crud/servicesCT.js, test/smoke/resourcesST.js
=> assercion with mongo

.gitignore, settings.json, test/crud/servicesCT.js
=> setting Update

test/crud/servicesCT.js, test/smoke/servicesSt.js
=> change the test name

lib/conferenceRoomsLib.js, requestJSONs/conferenceRoomsRequest.json, test/crud/conferenceRoomsCT.js
I update 6 test cases and 3 are still developing
=> Upload my crud test cases

lib/meetingsLib.js, test/crud/meetingsCT.js, test/smoke/resourcesST.js
Update of the CRUDs and the libraries to get the information of all the rooms of each environment
=> meeting feature CRUDs and library updated

test/crud/conferenceRoomsCT.js
=> Modify Crud

config/meetingsConfig.json, lib/meetingsLib.js
updating the libraries again :disappointed: :gun:
=> Update libraries AGAIN!!!

lib/mongoConnection.js, test/crud/locationsCT.js
GET method makes validations by DB
=> Locations crud tests fixed

lib/mongoConnection.js, test/crud/locationsCT.js
=> Revert "Locations crud tests fixed"

test/crud/conferenceRoomsCT.js, test/crud/impersonationCT.js
=> Added 2 CRUD tests cases for conference rooms.

.gitignore, requestJSONs/conferenceRoomsRequest.json, settings.json, test/crud/conferenceRoomsCT.js
Changes were on get, update and delete resources by room.
=> Added changes to conference rooms CRUD test cases.

lib/impersonationLib.js, test/crud/impersonationCT.js, test/smoke/impersonationST.js
These changes were being made on Friday, but they were not reflected in the code, so I'm uploading again.
=> Re-uploaded impersonation test cases.

test/crud/resourcesCT.js
Verification using the DB were added to the test case "Get all resources"
=> get all resources verification with the DB

test/functional/servicesFT.js, test/smoke/servicesSt.js
I upload two scenarios about the behavior of rooms with the service
=> scene services and room

lib/outOfOrderLib.js, test/crud/outOfOrderCT.js, test/functional/outOfOrderFT.js
A scenario of out-of-order  with conference room
=> A scenario of out-of-order  with conference room

test/functional/outOfOrderFT.js
=> Delete a line of require.

test/functional/codingDojo.js
=> codingDojo

test/functional/outOfOrderFT.js, test/smoke/outOfOrderST.js
and Smoke with different approach
=> Scenario of out-of-order with meeting
